from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_Window(object):
    def setupUi(self, add_Window):
        add_Window.setObjectName("add_Window")
        add_Window.resize(391, 175)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        add_Window.setFont(font)
        add_Window.setSizeGripEnabled(False)
        add_Window.setWindowIcon(QtGui.QIcon('icon/add.jpg'))
        self.widget = QtWidgets.QWidget(add_Window)
        self.widget.setGeometry(QtCore.QRect(80, 40, 139, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_line = QtWidgets.QLineEdit(self.widget)
        self.name_line.setObjectName("name_line")
        self.verticalLayout.addWidget(self.name_line)
        self.author_line = QtWidgets.QLineEdit(self.widget)
        self.author_line.setObjectName("author_line")
        self.verticalLayout.addWidget(self.author_line)
        self.pub_line = QtWidgets.QLineEdit(self.widget)
        self.pub_line.setObjectName("pub_line")
        self.verticalLayout.addWidget(self.pub_line)
        self.stand_line = QtWidgets.QLineEdit(self.widget)
        self.stand_line.setObjectName("stand_line")
        self.verticalLayout.addWidget(self.stand_line)
        self.widget1 = QtWidgets.QWidget(add_Window)
        self.widget1.setGeometry(QtCore.QRect(20, 40, 66, 111))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_name = QtWidgets.QLabel(self.widget1)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout_2.addWidget(self.lbl_name)
        self.lbl_author = QtWidgets.QLabel(self.widget1)
        self.lbl_author.setObjectName("lbl_author")
        self.verticalLayout_2.addWidget(self.lbl_author)
        self.lbl_pub = QtWidgets.QLabel(self.widget1)
        self.lbl_pub.setObjectName("lbl_pub")
        self.verticalLayout_2.addWidget(self.lbl_pub)
        self.lbl_stand = QtWidgets.QLabel(self.widget1)
        self.lbl_stand.setObjectName("lbl_stand")
        self.verticalLayout_2.addWidget(self.lbl_stand)
        self.widget2 = QtWidgets.QWidget(add_Window)
        self.widget2.setGeometry(QtCore.QRect(270, 50, 95, 65))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addbook_button = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.addbook_button.setFont(font)
        self.addbook_button.setAutoFillBackground(False)
        self.addbook_button.setDefault(True)
        self.addbook_button.setObjectName("addbook_button")
        self.verticalLayout_3.addWidget(self.addbook_button)
        self.addpageCancel_but = QtWidgets.QPushButton(self.widget2)
        self.addpageCancel_but.setObjectName("addpageCancel_but")
        self.verticalLayout_3.addWidget(self.addpageCancel_but)

        self.retranslateUi(add_Window)
        QtCore.QMetaObject.connectSlotsByName(add_Window)

    def retranslateUi(self, add_Window):
        _translate = QtCore.QCoreApplication.translate
        add_Window.setWindowTitle(_translate("add_Window", "Add Book"))
        self.lbl_name.setText(_translate("add_Window", "Name:"))
        self.lbl_author.setText(_translate("add_Window", "Author:"))
        self.lbl_pub.setText(_translate("add_Window", "Publisher:"))
        self.lbl_stand.setText(_translate("add_Window", "Stand:"))
        self.addbook_button.setToolTip(_translate("add_Window", "Add Book"))
        self.addbook_button.setText(_translate("add_Window", "Add Book"))
        self.addbook_button.setShortcut(_translate("add_Window", "Return"))
        self.addpageCancel_but.setText(_translate("add_Window", "Cancel"))

