from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_Window(object):
    def setupUi(self, search_Window):
        search_Window.setObjectName("search_Window")
        search_Window.resize(443, 212)
        search_Window.setWindowIcon(QtGui.QIcon('icon/search.png'))
        self.label = QtWidgets.QLabel(search_Window)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(search_Window)
        self.widget.setGeometry(QtCore.QRect(30, 40, 261, 144))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id_line = QtWidgets.QLineEdit(self.widget)
        self.id_line.setObjectName("id_line")
        self.verticalLayout_2.addWidget(self.id_line)
        self.name_line = QtWidgets.QLineEdit(self.widget)
        self.name_line.setObjectName("name_line")
        self.verticalLayout_2.addWidget(self.name_line)
        self.author_line = QtWidgets.QLineEdit(self.widget)
        self.author_line.setObjectName("author_line")
        self.verticalLayout_2.addWidget(self.author_line)
        self.pub_line = QtWidgets.QLineEdit(self.widget)
        self.pub_line.setObjectName("pub_line")
        self.verticalLayout_2.addWidget(self.pub_line)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.stand_box = QtWidgets.QComboBox(self.widget)
        self.stand_box.setEditable(True)
        self.stand_box.setCurrentText("")
        self.stand_box.setObjectName("stand_box")
        self.verticalLayout_3.addWidget(self.stand_box)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.widget1 = QtWidgets.QWidget(search_Window)
        self.widget1.setGeometry(QtCore.QRect(320, 60, 95, 65))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.search_but = QtWidgets.QPushButton(self.widget1)
        self.search_but.setObjectName("search_but")
        self.verticalLayout_4.addWidget(self.search_but)
        self.cancel_but = QtWidgets.QPushButton(self.widget1)
        self.cancel_but.setObjectName("cancel_but")
        self.verticalLayout_4.addWidget(self.cancel_but)

        self.retranslateUi(search_Window)
        QtCore.QMetaObject.connectSlotsByName(search_Window)

    def retranslateUi(self, search_Window):
        _translate = QtCore.QCoreApplication.translate
        search_Window.setWindowTitle(_translate("search_Window", "Search"))
        self.label.setText(_translate("search_Window", "Search with:"))
        self.label_5.setText(_translate("search_Window", "ID:"))
        self.label_2.setText(_translate("search_Window", "Name:"))
        self.label_3.setText(_translate("search_Window", "Author:"))
        self.label_4.setText(_translate("search_Window", "Publisher:"))
        self.label_6.setText(_translate("search_Window", "Stand:"))
        self.id_line.setPlaceholderText(_translate("search_Window", "Enter ID"))
        self.name_line.setPlaceholderText(_translate("search_Window", "Enter Name"))
        self.author_line.setPlaceholderText(_translate("search_Window", "Enter Author"))
        self.pub_line.setPlaceholderText(_translate("search_Window", "Enter Publisher"))
        self.search_but.setText(_translate("search_Window", "Search"))
        self.cancel_but.setText(_translate("search_Window", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    search_Window = QtWidgets.QDialog()
    ui = Ui_search_Window()
    ui.setupUi(search_Window)
    search_Window.show()
    sys.exit(app.exec_())
